ExpressTrain_WEB/config/routes.rb
Rails.application.routes.draw do
  get '/index' => 'apply#index'

  get 'apply/new'
  
  post 'apply/create'

  get 'apply/update/:apply_id' => 'apply#update'

  get 'apply/delete'

  get 'category/create'

  get 'category/delete'

  devise_for :members
  devise_scope :member do 
    get '/members/sign_out' , to: 'devise/sessions#destroy'
    get '/members/:id/edit' , to: 'members#edit'
    patch '/members/:id', to: 'members#update'
  end
  resources :members, only: [:new, :create, :edit, :update]
  
  root 'main#index'
  
  get '/map'=>'home#map'
 
  get '/list' =>'home#list'
  
  post '/finder' => 'home#list'
  
  get '/finder'=> 'home#list'
  
  get 'main/index'
  

end

ExpressTrain_WEB/app/models/apply.rb
class Apply < ActiveRecord::Base
    belongs_to :member
    belongs_to :category
end

ExpressTrain_WEB/app/models/category.rb
class Category < ActiveRecord::Base
end

ExpressTrain_WEB/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :comment_list
    belongs_to :member
end

ExpressTrain_WEB/app/models/comment_list.rb
class CommentList < ActiveRecord::Base
    belongs_to :menu
    has_many :comments
end

ExpressTrain_WEB/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments
  belongs_to :apply
end

ExpressTrain_WEB/app/models/menu.rb
class Menu < ActiveRecord::Base
    belongs_to :store
end

ExpressTrain_WEB/app/models/store.rb
class Store < ActiveRecord::Base
    belongs_to :category
    
end

ExpressTrain_WEB/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def map
    @stores = Store.all
  end

  def list
    if (params[:category] == nil) && (params[:card] == nil) && (params[:location] == nil)   # 체크 X
      @stores = Store.all
    elsif(params[:category] != nil) && (params[:card] == nil) && (params[:location] == nil) #카테고리만 체크
      @stores = Store.where({ category: params[:category]})
    end
  end

  def notice
  end
end

ExpressTrain_WEB/app/controllers/main_controller.rb
class MainController < ApplicationController
end

ExpressTrain_WEB/app/controllers/menu_controller.rb
class MenuController < ApplicationController
end

ExpressTrain_WEB/app/helpers/application_helper.rb
module ApplicationHelper
end

ExpressTrain_WEB/app/helpers/apply_helper.rb
module ApplyHelper
end

ExpressTrain_WEB/app/helpers/category_helper.rb
module CategoryHelper
end

ExpressTrain_WEB/app/helpers/comment_helper.rb
module CommentHelper
end

ExpressTrain_WEB/app/helpers/home_helper.rb
module HomeHelper
end

ExpressTrain_WEB/app/helpers/main_helper.rb
module MainHelper
end

ExpressTrain_WEB/app/helpers/member_helper.rb
module MemberHelper
end

ExpressTrain_WEB/app/helpers/menu_helper.rb
module MenuHelper
end

ExpressTrain_WEB/app/helpers/post_helper.rb
module PostHelper
end

ExpressTrain_WEB/app/helpers/store_helper.rb
module StoreHelper
end

ExpressTrain_WEB/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body> 

<header>
     <div class="container8">
        <nav class='nav-basic' id="nav-basic">
            <ul>
             
                <li>
                    <a href="/">HOME</a>
                </li>
                <li>
                    <a href="/list">STORE</a>
                </li>
                <li>
                    <a href="/index">APPLY</a>
                </li>

                <li>
                  <% if member_signed_in? %>
                    <a href="/members/sign_out">LOGOUT</a>
                  <% else %>
                    <a href="/members/sign_in">LOGIN</a>
                  <% end %>
                </li>
                <li>
                  <% unless member_signed_in? %>
                    <a href="/members/sign_up">SIGN UP</a>
                  <% end %>
                </li>
                        <div class="logo">  <p><img src="/assets/logo.png" width="72px" height="57px;">ExpressTrain</p></div>
            </ul>
        </nav>
        </div>
          <script>
        const myNav = document.getElementById('nav-basic')
 
        window.onscroll = function () {
            console.log(window.scrollY)
            if (window.scrollY >= 10) {
                myNav.className = 'nav-change';
            }
            else {
                myNav.className = 'nav-basic';
            }
        }
    </script>
    </header>
              
 
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div class="footer-main-div">
    
   <div class="footer-social-icons">
	    <ul>
		    <li><a href="https://www.facebook.com/"><img src="/assets/facebook.png" height="35em" width="35em"></a></li>
		    <li><a href="https://www.instagram.com/?hl=ko"><img src="/assets/instagram.png" height="35em" width="35em"></a></li>
		    <li><a href="https://www.youtube.com/"><img src="/assets/youtube.png" height="40em" width="35em"></a></li>
		    <li><a href="https://github.com/"><img src="/assets/github.png" height="35em" width="35em"></a></li>
	    </ul>
    </div>
 
    <div class="footer-menu-one">
    	<ul>
		    <li><a href="/">Home</a></li>
        <li><a href=" /list">STORE</a></li>
        <li><a href="/index">APPLY</a></li>
 	    </ul>
    </div>
 
    <div class="footer-menu-two">
	    <ul>
		 <li><a href="#">DEVELOPER</a></li>
         <li><a href="https://github.com/namsoo5">김남수</a></li>
         <li><a href="https://github.com/jaeryo2357">양민욱</a></li>
         <li><a href="https://github.com/tngusmiso">임수현</a></li>
         <li><a href="https://github.com/jangheeseung">장희승</a></li>
         <li><a href="https://github.com/HamJinKyoung">함진경</a></li>
 	    </ul>
    </div>
</div>
   
</body>
</html>